name: CrediTrust CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Create directories
        run: |
          mkdir -p data src/vector_store tests

      - name: Run linting
        run: |
          flake8 app_streamlit.py src/chunk_embed_index.py src/rag_pipeline.py tests/test_rag_pipeline.py --max-line-length=120 --exclude=.git,__pycache__,data,src/vector_store,notebooks,reports

      - name: Run tests
        run: |
          pytest tests/test_rag_pipeline.py
